# Generated by Django 4.0.6 on 2022-08-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrezelWars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=64)),
                ('player_one_username', models.CharField(max_length=128)),
                ('player_two_username', models.CharField(max_length=128)),
                ('player_one_points', models.IntegerField()),
                ('player_two_points', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('steps', models.CharField(max_length=1024)),
            ],
        ),
    ]
