# Generated by Django 4.0.6 on 2022-08-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrezelWars',
            new_name='BrezelWar',
        ),
    ]
